# Use a specific version of OpenJDK as the base image
FROM openjdk:17

# Set the working directory
WORKDIR /app

# Copy only necessary files
# COPY NeoCode.java /app

# # Compile the Java file
# RUN javac NeoCode.java

# # Specify the command to run the Java application
# CMD ["java", "NeoCode"]
